import type React from "react";
import { useMemo } from "react";
import * as Icons from "lucide-react";
import type { Link } from "@/types/config";
import { useConfig } from "@/hooks/useConfig";

interface LinkCardProps {
  link: Link;
  accentColor?: string;
}

// Map of icon names to lucide icons - only includes valid Lucide React icons
const iconMap: Record<string, React.ComponentType<any>> = {
  // Brand icons
  "brand-github": Icons.Github,
  "brand-gitlab": Icons.GitlabIcon,
  "brand-reddit": Icons.MessageCircle,
  "brand-youtube": Icons.Youtube,
  "brand-twitch": Icons.Twitch,
  "brand-mastodon": Icons.Rss,
  "brand-linkedin": Icons.Linkedin,
  "brand-twitter": Icons.Twitter,
  "brand-facebook": Icons.Facebook,
  "brand-instagram": Icons.Instagram,
  "brand-discord": Icons.MessageSquare,
  "brand-steam": Icons.Activity,
  "brand-spotify": Icons.Music,
  "brand-tidal": Icons.Music,
  "brand-soundcloud": Icons.Music,
  "brand-pinterest": Icons.Bookmark,
  "brand-pixiv": Icons.Image,
  "brand-artstation": Icons.Palette,
  "brand-aws": Icons.Cloud,
  "brand-vercel": Icons.Zap,
  "brand-docker": Icons.Box,
  "brand-openai": Icons.Zap,
  "brand-lastfm": Icons.Music,
  "brand-appgallery": Icons.Store,
  "brand-fortnite": Icons.Gamepad2,
  "brand-xbox": Icons.Gamepad2,
  "brand-speedtest": Icons.Zap,
  "brand-nord-vpn": Icons.Shield,
  "brand-campaignmonitor": Icons.Mail,
  "brand-slack": Icons.Slack,
  "brand-telegram": Icons.Send,
  "brand-whatsapp": Icons.MessageCircle,
  "brand-viber": Icons.Phone,
  "brand-wechat": Icons.MessageCircle,
  "brand-qq": Icons.MessageSquare,
  "brand-line": Icons.MessageSquare,
  "brand-signal": Icons.Lock,
  "brand-messenger": Icons.Send,
  "brand-skype": Icons.Phone,
  "brand-zoom": Icons.Video,
  "brand-google-meet": Icons.Video,
  "brand-jitsi": Icons.Video,

  // General icons
  mail: Icons.Mail,
  "calendar-filled": Icons.Calendar,
  lock: Icons.Lock,
  cloud: Icons.Cloud,
  search: Icons.Search,
  settings: Icons.Settings,
  menu: Icons.Menu,
  x: Icons.X,
  close: Icons.X,
  "arrow-right": Icons.ArrowRight,
  "arrow-left": Icons.ArrowLeft,
  check: Icons.Check,
  trash: Icons.Trash2,
  edit: Icons.Edit,
  copy: Icons.Copy,
  download: Icons.Download,
  upload: Icons.Upload,
  share: Icons.Share2,
  heart: Icons.Heart,
  star: Icons.Star,
  bookmark: Icons.Bookmark,
  bell: Icons.Bell,
  user: Icons.User,
  users: Icons.Users,
  inbox: Icons.Inbox,
  folder: Icons.Folder,
  file: Icons.File,
  news: Icons.Rss,
  article: Icons.FileText,
  book: Icons.Book,
  books: Icons.BookOpen,
  school: Icons.GraduationCap,
  code: Icons.Code,
  database: Icons.Database,
  server: Icons.Server,
  network: Icons.Wifi,
  device: Icons.Smartphone,
  "device-mobile": Icons.Smartphone,
  "device-gamepad": Icons.Gamepad2,
  "device-speaker": Icons.Speaker,
  headphones: Icons.Headphones,
  music: Icons.Music,
  ear: Icons.Ear,
  volume: Icons.Volume2,
  "device-tv": Icons.Tv,
  keyboard: Icons.Keyboard,
  mouse: Icons.Mouse,
  refresh: Icons.RefreshCw,
  reload: Icons.RefreshCw,
  sync: Icons.RotateCw,
  loading: Icons.Loader,
  spinner: Icons.Loader,
  clock: Icons.Clock,
  "calendar-time": Icons.Calendar,
  time: Icons.Clock,
  schedule: Icons.Clock,
  alert: Icons.AlertCircle,
  "alert-circle": Icons.AlertCircle,
  info: Icons.Info,
  help: Icons.HelpCircle,
  question: Icons.HelpCircle,
  warning: Icons.AlertTriangle,
  error: Icons.AlertOctagon,
  success: Icons.CheckCircle2,
  done: Icons.CheckCircle2,
  remove: Icons.X,
  add: Icons.Plus,
  plus: Icons.Plus,
  minus: Icons.Minus,
  more: Icons.MoreHorizontal,
  "more-vertical": Icons.MoreVertical,
  dots: Icons.MoreHorizontal,
  filter: Icons.Filter,
  sort: Icons.ArrowUpDown,
  grid: Icons.Grid,
  list: Icons.List,
  view: Icons.Eye,
  hide: Icons.EyeOff,
  show: Icons.Eye,
  "zoom-in": Icons.ZoomIn,
  "zoom-out": Icons.ZoomOut,
  focus: Icons.Focus,
  maximize: Icons.Maximize2,
  minimize: Icons.Minimize2,
  fullscreen: Icons.Maximize,
  unlock: Icons.Unlock,
  "lock-access": Icons.LockOpen,
  key: Icons.Key,
  password: Icons.Lock,
  shield: Icons.Shield,
  security: Icons.Shield,
  fingerprint: Icons.Fingerprint,
  certificate: Icons.Award,
  badge: Icons.Award,
  trophy: Icons.Trophy,
  medal: Icons.Award,
  crown: Icons.Crown,
  flask: Icons.Beaker,
  "test-tube": Icons.Beaker,
  atom: Icons.Atom,
  dna: Icons.Dna,
  calculator: Icons.Calculator,
  puzzle: Icons.Puzzle,
  circle: Icons.Circle,
  square: Icons.Square,
  triangle: Icons.Triangle,
  map: Icons.Map,
  "map-pin": Icons.MapPin,
  compass: Icons.Compass,
  navigation: Icons.Navigation,
  directions: Icons.Navigation,
  language: Icons.Languages,
  translate: Icons.Languages,
  globe: Icons.Globe,
  world: Icons.Globe,
  earth: Icons.Globe,
  sun: Icons.Sun,
  moon: Icons.Moon,
  "cloud-rain": Icons.CloudRain,
  rain: Icons.CloudRain,
  wind: Icons.Wind,
  storm: Icons.CloudLightning,
  lightning: Icons.Zap,
  bolt: Icons.Zap,
  fire: Icons.Flame,
  water: Icons.Droplets,
  droplet: Icons.Droplets,
  palette: Icons.Palette,
  "color-picker": Icons.Pipette,
  adjustments: Icons.Sliders,
  brightness: Icons.Sun,
  contrast: Icons.Contrast,
  box: Icons.Box,
  boxes: Icons.Boxes,
  briefcase: Icons.Briefcase,
  building: Icons.Building2,
  "building-store": Icons.Store,
  "building-factory": Icons.Factory,
  home: Icons.Home,
  house: Icons.Home,
  apartment: Icons.Building2,
  "door-open": Icons.DoorOpen,
  window: Icons.Square,
  roof: Icons.Triangle,
  money: Icons.DollarSign,
  currency: Icons.DollarSign,
  "currency-dollar": Icons.DollarSign,
  "currency-euro": Icons.Euro,
  "currency-pound": Icons.PoundSterling,
  cash: Icons.Coins,
  coins: Icons.Coins,
  wallet: Icons.Wallet,
  "credit-card": Icons.CreditCard,
  receipt: Icons.Receipt,
  bank: Icons.Landmark,
  percent: Icons.Percent,
  percentage: Icons.Percent,
  ratio: Icons.Ratio,
  number: Icons.Hash,
  count: Icons.Hash,
  counter: Icons.Hash,
  hash: Icons.Hash,
  pencil: Icons.PencilLine,
  brush: Icons.Brush,
  eraser: Icons.Eraser,
  highlighter: Icons.Highlighter,
  marker: Icons.Pen,
  pen: Icons.Pen,
  typewriter: Icons.Type,
  "keyboard-hide": Icons.Keyboard,
  "keyboard-show": Icons.Keyboard,
  skull: Icons.Skull,
  spray: Icons.Droplet,
  "server-off": Icons.ServerOff,
  brain: Icons.Brain,
  eye: Icons.Eye,
  "eye-off": Icons.EyeOff,
  pdf: Icons.FileText,
  "file-pdf": Icons.FileText,
  "file-spreadsheet": Icons.Sheet,
  "file-document": Icons.FileText,
  "file-zip": Icons.Archive,
  "file-code": Icons.Code,
  "file-multiple": Icons.Files,
  files: Icons.Files,
  "hard-drive": Icons.HardDrive,
  "hard-drive-2": Icons.HardDrive,
  ssd: Icons.HardDrive,
  cd: Icons.Disc3,
  dvd: Icons.Disc3,
  disc: Icons.Disc3,
  usb: Icons.Usb,
  "sim-card": Icons.Smartphone,
  "arrow-up": Icons.ArrowUp,
  "arrow-down": Icons.ArrowDown,
  "arrow-maximize": Icons.Maximize,
  "arrow-minimize": Icons.Minimize,
  chevron: Icons.ChevronDown,
  "chevron-up": Icons.ChevronUp,
  "chevron-down": Icons.ChevronDown,
  "chevron-left": Icons.ChevronLeft,
  "chevron-right": Icons.ChevronRight,
  "angle-up": Icons.ArrowUp,
  "angle-down": Icons.ArrowDown,
  "angle-left": Icons.ArrowLeft,
  "angle-right": Icons.ArrowRight,
  "caret-up": Icons.ChevronUp,
  "caret-down": Icons.ChevronDown,
  "caret-left": Icons.ChevronLeft,
  "caret-right": Icons.ChevronRight,
  "corner-down-left": Icons.CornerDownLeft,
  "corner-down-right": Icons.CornerDownRight,
  "corner-up-left": Icons.CornerUpLeft,
  "corner-up-right": Icons.CornerUpRight,
  pause: Icons.Pause,
  play: Icons.Play,
  stop: Icons.Square,
  "fast-forward": Icons.SkipForward,
  rewind: Icons.SkipBack,
  next: Icons.SkipForward,
  previous: Icons.SkipBack,
  loop: Icons.RotateCw,
  repeat: Icons.RotateCw,
  shuffle: Icons.Shuffle,
  "volume-off": Icons.VolumeX,
  "volume-down": Icons.Volume1,
  "volume-up": Icons.Volume2,
  mute: Icons.VolumeX,
  unmute: Icons.Volume2,
  microphone: Icons.Mic,
  "microphone-off": Icons.MicOff,
  phone: Icons.Phone,
  "phone-call": Icons.Phone,
  "phone-incoming": Icons.PhoneIncoming,
  "phone-outgoing": Icons.PhoneOutgoing,
  "phone-missed": Icons.PhoneMissed,
  "phone-off": Icons.PhoneOff,
  sms: Icons.MessageSquare,
  message: Icons.MessageSquare,
  "message-circle": Icons.MessageCircle,
  messages: Icons.MessageSquare,
  chat: Icons.MessageSquare,
  "chat-bubble": Icons.MessageCircle,
  "chat-bubbles": Icons.MessageSquare,
  conversation: Icons.MessageSquare,
  comment: Icons.MessageSquare,
  comments: Icons.MessageSquare,
  video: Icons.Video,
  "video-off": Icons.VideoOff,
  live: Icons.Dot,
  broadcast: Icons.Radio,
  podcast: Icons.Radio,
  rss: Icons.Rss,
  feed: Icons.Rss,
  antenna: Icons.Radio,
  signal: Icons.Radio,
  wifi: Icons.Wifi,
  "wifi-off": Icons.WifiOff,
  bluetooth: Icons.Bluetooth,
  satellite: Icons.Satellite,
  gps: Icons.MapPin,
  locate: Icons.MapPin,
  pointer: Icons.MousePointer,
  cursor: Icons.MousePointer,
  hand: Icons.Hand,
  "thumbs-up": Icons.ThumbsUp,
  "thumbs-down": Icons.ThumbsDown,
  "fingers-crossed": Icons.Hand,
  fist: Icons.Hand,
  "raised-hand": Icons.Hand,
};

export const LinkCard: React.FC<LinkCardProps> = ({ link, accentColor }) => {
  const { config } = useConfig();

  const IconComponent = useMemo(() => {
    if (!link.icon) return null;
    return iconMap[link.icon as keyof typeof iconMap];
  }, [link.icon]);

  return (
    <a
      href={link.url}
      target='_blank'
      rel='noopener noreferrer'
      className='inline-flex items-center gap-2 px-4 py-2.5 bg-mantle/80 backdrop-blur-sm rounded-lg shadow-lg hover:shadow-xl hover:bg-mantle hover:translate-y-0.5 transition-all duration-150 group border border-surface0/30 hover:border-surface0/60'
    >
      {IconComponent && (
        <IconComponent
          className='w-4 h-4 flex-shrink-0'
          color={link.icon_color || config.palette?.text}
        />
      )}

      {link.name && (
        <span className='text-text font-semibold text-xs group-hover:text-[--accent-color] transition-colors whitespace-nowrap'>
          {link.name}
        </span>
      )}

      <style>{`
        a[href]:has(span) {
          --accent-color: ${accentColor || config.palette?.green};
        }
      `}</style>
    </a>
  );
};
