import { palettes } from '@/lib/palette';
import type { Config } from '@/types/config';

export const CONFIG_VERSION = "2.0.0";

export const defaultConfig: Config = {
  overrideStorage: true,
  temperature: {
    location: 'Surabaya',
    scale: 'C',
    enabled: true,
  },
  clock: {
    format: 'h:i p',
    iconColor: palettes.macchiato.maroon,
    enabled: true,
  },
  disabled: [],
  fastlink: '',
  openLastVisitedTab: false,
  lastVisitedTab: 0,
  currentPalette: 'macchiato',
  palette: palettes.macchiato,
  tabs: [
    {
      id: 'personal',
      name: 'personal',
      background_url: '/images/banners/personal-bg.gif',
      categories: [
        {
          id: 'personal-social',
          name: 'Social Media',
        },
        {
          id: 'personal-entertainment',
          name: 'Entertainment',
        },
        {
          id: 'personal-productivity',
          name: 'Productivity',
        },
        {
          id: 'personal-cloud',
          name: 'Cloud Services',
        },
      ],
      links: [
        // Social Media
        {
          id: 'p-1',
          name: 'mastodon',
          url: 'https://mastodon.social',
          icon: 'brand-mastodon',
          icon_color: palettes.macchiato.green,
          category_id: 'personal-social',
        },
        {
          id: 'p-2',
          name: 'reddit',
          url: 'https://www.reddit.com/',
          icon: 'brand-reddit',
          icon_color: palettes.macchiato.peach,
          category_id: 'personal-social',
        },
        {
          id: 'p-3',
          name: 'twitter',
          url: 'https://twitter.com',
          icon: 'brand-twitter',
          icon_color: palettes.macchiato.blue,
          category_id: 'personal-social',
        },
        {
          id: 'p-4',
          name: 'instagram',
          url: 'https://www.instagram.com/',
          icon: 'brand-instagram',
          icon_color: palettes.macchiato.pink,
          category_id: 'personal-social',
        },
        // Entertainment
        {
          id: 'p-5',
          name: 'youtube',
          url: 'https://www.youtube.com/',
          icon: 'brand-youtube',
          icon_color: palettes.macchiato.red,
          category_id: 'personal-entertainment',
        },
        {
          id: 'p-6',
          name: 'twitch',
          url: 'https://www.twitch.tv/',
          icon: 'brand-twitch',
          icon_color: palettes.macchiato.lavender,
          category_id: 'personal-entertainment',
        },
        {
          id: 'p-7',
          name: 'spotify',
          url: 'https://open.spotify.com',
          icon: 'brand-spotify',
          icon_color: palettes.macchiato.green,
          category_id: 'personal-entertainment',
        },
        {
          id: 'p-8',
          name: 'netflix',
          url: 'https://www.netflix.com',
          icon: 'play',
          icon_color: palettes.macchiato.red,
          category_id: 'personal-entertainment',
        },
        // Productivity
        {
          id: 'p-9',
          name: 'mail',
          url: 'https://mail.proton.me',
          icon: 'mail',
          icon_color: palettes.macchiato.green,
          category_id: 'personal-productivity',
        },
        {
          id: 'p-10',
          name: 'calendar',
          url: 'https://calendar.proton.me',
          icon: 'calendar-filled',
          icon_color: palettes.macchiato.peach,
          category_id: 'personal-productivity',
        },
        {
          id: 'p-11',
          name: 'notion',
          url: 'https://www.notion.so',
          icon: 'database',
          icon_color: palettes.macchiato.text,
          category_id: 'personal-productivity',
        },
        {
          id: 'p-12',
          name: 'todoist',
          url: 'https://todoist.com',
          icon: 'checkbox',
          icon_color: palettes.macchiato.red,
          category_id: 'personal-productivity',
        },
        // Cloud Services
        {
          id: 'p-13',
          name: 'drive',
          url: 'https://drive.proton.me',
          icon: 'cloud',
          icon_color: palettes.macchiato.blue,
          category_id: 'personal-cloud',
        },
        {
          id: 'p-14',
          name: 'vault',
          url: 'https://vault.bitwarden.com',
          icon: 'lock',
          icon_color: palettes.macchiato.red,
          category_id: 'personal-cloud',
        },
        {
          id: 'p-15',
          name: 'icloud',
          url: 'https://www.icloud.com',
          icon: 'cloud',
          icon_color: palettes.macchiato.lavender,
          category_id: 'personal-cloud',
        },
      ],
    },
    {
      id: 'dev',
      name: 'dev',
      background_url: '/images/banners/dev-bg.gif',
      categories: [
        {
          id: 'dev-code',
          name: 'Code & Repositories',
        },
        {
          id: 'dev-tools',
          name: 'Development Tools',
        },
        {
          id: 'dev-design',
          name: 'Design & Assets',
        },
        {
          id: 'dev-learning',
          name: 'Learning',
        },
      ],
      links: [
        // Code & Repositories
        {
          id: 'd-1',
          name: 'github',
          url: 'https://github.com',
          icon: 'brand-github',
          icon_color: palettes.macchiato.text,
          category_id: 'dev-code',
        },
        {
          id: 'd-2',
          name: 'gitlab',
          url: 'https://gitlab.com',
          icon: 'brand-gitlab',
          icon_color: palettes.macchiato.peach,
          category_id: 'dev-code',
        },
        {
          id: 'd-3',
          name: 'bitbucket',
          url: 'https://bitbucket.org',
          icon: 'code',
          icon_color: palettes.macchiato.blue,
          category_id: 'dev-code',
        },
        {
          id: 'd-4',
          name: 'codepen',
          url: 'https://codepen.io',
          icon: 'code',
          icon_color: palettes.macchiato.sky,
          category_id: 'dev-code',
        },
        // Development Tools
        {
          id: 'd-5',
          name: 'vscode',
          url: 'https://code.visualstudio.com',
          icon: 'code',
          icon_color: palettes.macchiato.blue,
          category_id: 'dev-tools',
        },
        {
          id: 'd-6',
          name: 'npm',
          url: 'https://www.npmjs.com',
          icon: 'package',
          icon_color: palettes.macchiato.red,
          category_id: 'dev-tools',
        },
        {
          id: 'd-7',
          name: 'docker',
          url: 'https://www.docker.com',
          icon: 'brand-docker',
          icon_color: palettes.macchiato.blue,
          category_id: 'dev-tools',
        },
        {
          id: 'd-8',
          name: 'vercel',
          url: 'https://vercel.com',
          icon: 'brand-vercel',
          icon_color: palettes.macchiato.text,
          category_id: 'dev-tools',
        },
        // Design & Assets
        {
          id: 'd-9',
          name: 'figma',
          url: 'https://www.figma.com',
          icon: 'palette',
          icon_color: palettes.macchiato.sky,
          category_id: 'dev-design',
        },
        {
          id: 'd-10',
          name: 'unsplash',
          url: 'https://unsplash.com',
          icon: 'image',
          icon_color: palettes.macchiato.blue,
          category_id: 'dev-design',
        },
        {
          id: 'd-11',
          name: 'pexels',
          url: 'https://www.pexels.com',
          icon: 'image',
          icon_color: palettes.macchiato.green,
          category_id: 'dev-design',
        },
        {
          id: 'd-12',
          name: 'icons8',
          url: 'https://icons8.com',
          icon: 'star',
          icon_color: palettes.macchiato.yellow,
          category_id: 'dev-design',
        },
        // Learning
        {
          id: 'd-13',
          name: 'stack overflow',
          url: 'https://stackoverflow.com',
          icon: 'help-circle',
          icon_color: palettes.macchiato.peach,
          category_id: 'dev-learning',
        },
        {
          id: 'd-14',
          name: 'dev.to',
          url: 'https://dev.to',
          icon: 'article',
          icon_color: palettes.macchiato.text,
          category_id: 'dev-learning',
        },
        {
          id: 'd-15',
          name: 'udemy',
          url: 'https://www.udemy.com',
          icon: 'book',
          icon_color: palettes.macchiato.mauve,
          category_id: 'dev-learning',
        },
        {
          id: 'd-16',
          name: 'mdn',
          url: 'https://developer.mozilla.org',
          icon: 'book',
          icon_color: palettes.macchiato.peach,
          category_id: 'dev-learning',
        },
      ],
    },
    {
      id: 'work',
      name: 'work',
      background_url: '/images/banners/work-bg.gif',
      categories: [
        {
          id: 'work-communication',
          name: 'Communication',
        },
        {
          id: 'work-management',
          name: 'Project Management',
        },
        {
          id: 'work-documents',
          name: 'Documents',
        },
      ],
      links: [
        // Communication
        {
          id: 'w-1',
          name: 'slack',
          url: 'https://slack.com',
          icon: 'brand-slack',
          icon_color: palettes.macchiato.sky,
          category_id: 'work-communication',
        },
        {
          id: 'w-2',
          name: 'discord',
          url: 'https://discord.com',
          icon: 'brand-discord',
          icon_color: palettes.macchiato.lavender,
          category_id: 'work-communication',
        },
        {
          id: 'w-3',
          name: 'telegram',
          url: 'https://web.telegram.org',
          icon: 'brand-telegram',
          icon_color: palettes.macchiato.blue,
          category_id: 'work-communication',
        },
        {
          id: 'w-4',
          name: 'zoom',
          url: 'https://zoom.us',
          icon: 'brand-zoom',
          icon_color: palettes.macchiato.blue,
          category_id: 'work-communication',
        },
        // Project Management
        {
          id: 'w-5',
          name: 'asana',
          url: 'https://asana.com',
          icon: 'checkbox',
          icon_color: palettes.macchiato.blue,
          category_id: 'work-management',
        },
        {
          id: 'w-6',
          name: 'jira',
          url: 'https://jira.atlassian.com',
          icon: 'target',
          icon_color: palettes.macchiato.blue,
          category_id: 'work-management',
        },
        {
          id: 'w-7',
          name: 'trello',
          url: 'https://trello.com',
          icon: 'grid',
          icon_color: palettes.macchiato.sky,
          category_id: 'work-management',
        },
        // Documents
        {
          id: 'w-8',
          name: 'google docs',
          url: 'https://docs.google.com',
          icon: 'file-text',
          icon_color: palettes.macchiato.sky,
          category_id: 'work-documents',
        },
        {
          id: 'w-9',
          name: 'sheets',
          url: 'https://sheets.google.com',
          icon: 'file-spreadsheet',
          icon_color: palettes.macchiato.green,
          category_id: 'work-documents',
        },
        {
          id: 'w-10',
          name: 'pdf tools',
          url: 'https://smallpdf.com',
          icon: 'file-pdf',
          icon_color: palettes.macchiato.red,
          category_id: 'work-documents',
        },
      ],
    },
    {
      id: 'creative',
      name: 'creative',
      background_url: '/images/banners/creative-bg.gif',
      categories: [
        {
          id: 'creative-design',
          name: 'Design Tools',
        },
        {
          id: 'creative-content',
          name: 'Content Creation',
        },
        {
          id: 'creative-inspiration',
          name: 'Inspiration',
        },
      ],
      links: [
        // Design Tools
        {
          id: 'c-1',
          name: 'adobe xd',
          url: 'https://www.adobe.com/products/xd.html',
          icon: 'palette',
          icon_color: palettes.macchiato.pink,
          category_id: 'creative-design',
        },
        {
          id: 'c-2',
          name: 'photoshop',
          url: 'https://www.adobe.com/products/photoshop.html',
          icon: 'image',
          icon_color: palettes.macchiato.sky,
          category_id: 'creative-design',
        },
        {
          id: 'c-3',
          name: 'canva',
          url: 'https://www.canva.com',
          icon: 'palette',
          icon_color: palettes.macchiato.sky,
          category_id: 'creative-design',
        },
        // Content Creation
        {
          id: 'c-4',
          name: 'youtube studio',
          url: 'https://studio.youtube.com',
          icon: 'brand-youtube',
          icon_color: palettes.macchiato.red,
          category_id: 'creative-content',
        },
        {
          id: 'c-5',
          name: 'tiktok',
          url: 'https://www.tiktok.com',
          icon: 'play',
          icon_color: palettes.macchiato.text,
          category_id: 'creative-content',
        },
        {
          id: 'c-6',
          name: 'twitch creator',
          url: 'https://dashboard.twitch.tv',
          icon: 'brand-twitch',
          icon_color: palettes.macchiato.lavender,
          category_id: 'creative-content',
        },
        // Inspiration
        {
          id: 'c-7',
          name: 'pinterest',
          url: 'https://www.pinterest.com',
          icon: 'brand-pinterest',
          icon_color: palettes.macchiato.red,
          category_id: 'creative-inspiration',
        },
        {
          id: 'c-8',
          name: 'dribbble',
          url: 'https://dribbble.com',
          icon: 'circle',
          icon_color: palettes.macchiato.pink,
          category_id: 'creative-inspiration',
        },
        {
          id: 'c-9',
          name: 'behance',
          url: 'https://www.behance.net',
          icon: 'star',
          icon_color: palettes.macchiato.sky,
          category_id: 'creative-inspiration',
        },
      ],
    },
  ],
};
