import type { Config } from "@/types/config";
import { palettes } from "@/lib/palette";

export const defaultConfig: Config = {
  overrideStorage: true,
  temperature: {
    location: "Surabaya",
    scale: "C",
    enabled: true,
  },
  clock: {
    format: "h:i p",
    iconColor: palettes.macchiato.maroon,
    enabled: true,
  },
  disabled: [],
  fastlink: "",
  openLastVisitedTab: false,
  lastVisitedTab: 0,
  currentPalette: "macchiato",
  palette: palettes.macchiato,
  tabs: [
    {
      id: "personal",
      name: "personal",
      background_url: "/images/banners/cbg-07.gif",
      categories: [
        {
          id: "media",
          name: "Media",
        },
        {
          id: "workspace",
          name: "workspace",
        },
      ],
      links: [
        {
          id: "link-1",
          name: "mastodon",
          url: "https://mastodon.social",
          icon: "brand-mastodon",
          icon_color: palettes.macchiato.green,
          category_id: "media",
        },
        {
          id: "link-2",
          name: "reddit",
          url: "https://www.reddit.com/",
          icon: "brand-reddit",
          icon_color: palettes.macchiato.peach,
          category_id: "media",
        },
        {
          id: "link-3",
          name: "youtube",
          url: "https://www.youtube.com/",
          icon: "brand-youtube",
          icon_color: palettes.macchiato.red,
          category_id: "media",
        },
        {
          id: "link-4",
          name: "twitch",
          url: "https://www.twitch.tv/",
          icon: "brand-twitch",
          icon_color: palettes.macchiato.blue,
          category_id: "media",
        },
        {
          id: "link-5",
          name: "hacker-news",
          url: "https://news.ycombinator.com/ask",
          icon: "news",
          icon_color: palettes.macchiato.mauve,
          category_id: "media",
        },
        {
          id: "link-6",
          name: "lemmy",
          url: "https://lemmy.ml/",
          icon: "users",
          icon_color: palettes.macchiato.sky,
          category_id: "media",
        },
        {
          id: "link-7",
          name: "mail",
          url: "https://mail.proton.me",
          icon: "brand-campaignmonitor",
          icon_color: palettes.macchiato.green,
          category_id: "workspace",
        },
        {
          id: "link-8",
          name: "calendar",
          url: "https://calendar.proton.me",
          icon: "calendar-filled",
          icon_color: palettes.macchiato.peach,
          category_id: "workspace",
        },
        {
          id: "link-9",
          name: "vault",
          url: "https://vault.bitwarden.com",
          icon: "lock",
          icon_color: palettes.macchiato.red,
          category_id: "workspace",
        },
        {
          id: "link-10",
          name: "drive",
          url: "https://drive.proton.me",
          icon: "cloud",
          icon_color: palettes.macchiato.blue,
          category_id: "workspace",
        },
      ],
    },
    {
      id: "dev",
      name: "dev",
      background_url: "/images/banners/cbg-08.gif",
      categories: [
        {
          id: "dev-media",
          name: "Media",
        },
      ],
      links: [
        {
          id: "dev-link-1",
          name: "github",
          url: "https://github.com",
          icon: "brand-github",
          icon_color: palettes.macchiato.green,
          category_id: "dev-media",
        },
        {
          id: "dev-link-2",
          name: "dev-community",
          url: "https://dev.to/",
          icon: "article",
          icon_color: palettes.macchiato.peach,
          category_id: "dev-media",
        },
        {
          id: "dev-link-3",
          name: "wakatime",
          url: "https://wakatime.com",
          icon: "clock",
          icon_color: palettes.macchiato.red,
          category_id: "dev-media",
        },
        {
          id: "dev-link-4",
          name: "dotfyle",
          url: "https://dotfyle.com/",
          icon: "puzzle",
          icon_color: palettes.macchiato.blue,
          category_id: "dev-media",
        },
      ],
    },
  ],
};
